qubic_wallet: QYBQUMAPZZTFCGGTGAUYUECQTLGCUXPOGBHVGPPNUECJXLOPUYPTQIDGQSQI
qubic_li_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImM5ZmQyZDM3LWVkNzYtNGRjMy05NTM3LTI4OTcwNWEzMGRlOSIsIk1pbmluZyI6IiIsIm5iZiI6MTcxMjc3NDczNSwiZXhwIjoxNzQ0MzEwNzM1LCJpYXQiOjE3MTI3NzQ3MzUsImlzcyI6Imh0dHBzOi8vcXViaWMubGkvIiwiYXVkIjoiaHR0cHM6Ly9xdWJpYy5saS8ifQ.qEf4gO1Vota-hIRsd1Pa6h6e7dmjzC_rM9oWh1FOd56UpcPxttWcoPEkkgb6OAuo9sROdDSGH8HoVWluWZdHXw

miners:
  qubic-li:
    state: started
    enabled: yes
  qubic-solutions:
    state: stopped
    enabled: no
  xmrig: 
    state: stopped
    enabled: no
    url: de.zephyr.herominers.com:1124
    user: ZEPHs8zp3a7gMhPpktyhtVbUM2RZrV8zfTGNYp2z1xrzgBJ9CwTxJqfjdAiQtB38NWP898JeoG9HQFuAbBSu2vQFQJ7kkqpFcJ3
    pass: "{{ inventory_hostname }}"