- hosts: octopus
  user: ubuntu
  roles:
    - role: bootstrap-os
      tags:
        - bootstrap
        - bootstrap-os

    - role: bootstrap-miners
      tags:
        - bootstrap
        - bootstrap-miners

    - role: qubic-solutions
      tags:
        - bootstrap
        - qubic-solutions

    - role: qubic-li
      tags:
        - bootstrap
        - qubic-li

    - role: xmrig
      tags:
        - bootstrap
        - xmrig

    - role: rplant
      tags:
        - bootstrap
        - rplant

    - role: srb
      tags:
        - bootstrap
        - srb

    - role: qubic-apool
      tags:
        - bootstrap
        - qubic-apool

    - role: qubic-pro
      tags:
        - bootstrap
        - qubic-pro

    - role: qubic-ninja
      tags:
        - bootstrap
        - qubic-ninja

    - role: cpuminer-flex
      tags:
        - bootstrap
        - cpuminer-flex

    - role: activate
      tags:
        - activate
        - always

# - hosts: skyler
#   user: ubuntu
#   roles:
#     - role: bootstrap-os
#       tags:
#         - bootstrap
#         - bootstrap-new

#     - role: xelis-node
#       tags:
#         - xelis-node

#     - role: xelis-proxy
#       tags:
#         - xelis-proxy

#     - role: docker
#       tags: 
#         - docker