- name: Copy service shell script
  ansible.builtin.copy:
    src: qli-Service.sh
    dest: /opt/miners/qubic-li/qli-Service.sh
    mode: u=rx,g=rx,o=
    owner: qubic-li
    group: miners
  become: yes

#TODO: use https://docs.ansible.com/ansible/latest/collections/ansible/posix/sysctl_module.html
- name: Update number of huge pages
  ansible.builtin.shell:
    cmd: "/sbin/sysctl -w vm.nr_hugepages={{ 92 * ansible_processor_cores * ansible_processor_threads_per_core }}"
  become: yes