- name: Reload systemd
  systemd:
    state: reloaded
  become: yes

- name: Restart miners
  ansible.builtin.service:
    name: "{{ item.key }}"
    state: "{{ 'started' if item.key == active_miner else 'stopped' }}"
    enabled: "{{ item.key == active_miner }}"
  loop: "{{ miners | dict2items }}"
  become: yes